// pages/login.vue
<script setup>
const credentials = ref({
  username: "",
  password: "",
});
const error = ref(null);
const router = useRouter();
const loginAttempts = ref(0);

const handleSubmit = async () => {
  try {
    const response = await $fetch("/api/auth/login", {
      method: "POST",
      body: credentials.value,
    });

    localStorage.setItem("user", JSON.stringify(response));
    loginAttempts.value = 0;
    router.push("/admin");
  } catch (error) {
    loginAttempts.value++;
    error.value = error.data?.message || "Đăng nhập thất bại";
  }
};

const initSampleData = async () => {
  try {
    const response = await $fetch("/api/seed", {
      method: "POST",
    });
    console.log(response.message);
  } catch (error) {
    console.error("Error initializing data:", error);
  }
};

// Tự động khởi tạo khi load trang
onMounted(() => {
  initSampleData();
});

// Tính năng tự động reset số lần đăng nhập sai sau 5 phút
let resetTimer;
watch(loginAttempts, (newValue) => {
  if (newValue > 0) {
    clearTimeout(resetTimer);
    resetTimer = setTimeout(
      () => {
        loginAttempts.value = 0;
      },
      5 * 60 * 1000
    ); // 5 phút
  }
});

onUnmounted(() => {
  clearTimeout(resetTimer);
});
</script>

<template>
  <div
    class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-12 px-4 sm:px-6 lg:px-8"
  >
    <div class="max-w-md mx-auto bg-white rounded-xl shadow-lg overflow-hidden">
      <div class="px-8 py-10">
        <h2 class="text-3xl font-bold text-center text-black mb-8">
          Đăng nhập hệ thống
        </h2>

        <!-- Thông báo -->
        <div
          v-if="error"
          class="mb-6 bg-red-50 border-l-4 border-red-400 p-4 rounded"
        >
          <div class="flex">
            <div class="flex-shrink-0">
              <svg
                class="h-5 w-5 text-red-400"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fill-rule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                  clip-rule="evenodd"
                />
              </svg>
            </div>
            <div class="ml-3">
              <p class="text-sm text-red-700">{{ error }}</p>
            </div>
          </div>
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-6">
          <div>
            <label class="block text-sm font-medium text-black">
              Tên đăng nhập
            </label>
            <input
              type="text"
              v-model="credentials.username"
              class="text-black mt-1 block w-full px-4 py-3 bg-gray-50 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-black">
              Mật khẩu
            </label>
            <input
              type="password"
              v-model="credentials.password"
              class="text-black mt-1 block w-full px-4 py-3 bg-gray-50 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>

          <button
            type="submit"
            class="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gradient-to-r from-blue-500 to-indigo-600 hover:from-blue-600 hover:to-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-all duration-200"
          >
            Đăng nhập
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

// src/components/Login.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";

const API_URL = "http://localhost:5000/api/auth";

const Login = () => {
  const [credentials, setCredentials] = useState({
    username: "",
    password: "",
  });
  const [error, setError] = useState(null);
  const navigate = useNavigate();

  const handleChange = (e) => {
    setCredentials({
      ...credentials,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post(`${API_URL}/login`, credentials);
      localStorage.setItem("user", JSON.stringify(response.data));
      navigate("/admin");
    } catch (error) {
      setError(error.response?.data?.message || "Đăng nhập thất bại");
    }
  };

  return (
    <div className="max-w-md mx-auto mt-12 p-6 bg-white rounded-lg shadow-md">
      <form onSubmit={handleSubmit}>
        <h2 className="text-2xl font-bold mb-6 text-center text-black-800">
          Đăng nhập
        </h2>
        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
            {error}
          </div>
        )}
        <div className="mb-4">
          <label className="block text-black text-sm font-bold mb-2">
            Tên đăng nhập:
          </label>
          <input
            type="text"
            name="username"
            value={credentials.username}
            onChange={handleChange}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <div className="mb-6">
          <label className="block text-black text-sm font-bold mb-2">
            Mật khẩu:
          </label>
          <input
            type="password"
            name="password"
            value={credentials.password}
            onChange={handleChange}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <button
          type="submit"
          className="w-full bg-blue-500 text-black font-bold py-2 px-4 rounded-md hover:bg-blue-600 transition duration-200"
        >
          Đăng nhập
        </button>
      </form>
    </div>
  );
};

export default Login;
